apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - image: ghcr.io/gethomepage/homepage:latest
          name: homepage
          ports:
            - containerPort: 3000
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "localhost"
            - name: PUID
              value: "1001"
            - name: PGID
              value: "1002"
          volumeMounts:
            - mountPath: /app/config
              name: homepage-config
            # - mountPath: /app/config/custom.js
            #   name: homepage-config
            #   subPath: custom.js
            # - mountPath: /app/config/custom.css
            #   name: homepage-config
            #   subPath: custom.css
            # - mountPath: /app/config/bookmarks.yaml
            #   name: homepage-config
            #   subPath: bookmarks.yaml
            # - mountPath: /app/config/docker.yaml
            #   name: homepage-config
            #   subPath: docker.yaml
            # - mountPath: /app/config/kubernetes.yaml
            #   name: homepage-config
            #   subPath: kubernetes.yaml
            # - mountPath: /app/config/services.yaml
            #   name: homepage-config
            #   subPath: services.yaml
            # - mountPath: /app/config/settings.yaml
            #   name: homepage-config
            #   subPath: settings.yaml
            # - mountPath: /app/config/widgets.yaml
            #   name: homepage-config
            #   subPath: widgets.yaml
            # - mountPath: /app/config/logs
            #   name: homepage-config
      volumes:
        - name: homepage-config
          persistentVolumeClaim:
            claimName: homepage-config
