apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        - name: registry-certs
          mountPath: "/certs"
          readOnly: true
        - name: registry-auth
          mountPath: "/auth"
          readOnly: true
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data-pvc
      - name: registry-certs
        secret:
          secretName: registry-cert
      - name: registry-auth
        secret:
          secretName: registry-auth
