apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "registry"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: docker-registry
  ports:
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
