# Internal MetalLM ip for nodes
apiVersion: v1
kind: Service
metadata:
  name: registry-ip
  namespace: registry
spec:
  type: LoadBalancer
  selector:
    app: docker-registry
  ports:
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
---
# External Tailscale LoadBalancer for pushing from outside
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "registry"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: docker-registry
  ports:
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
