apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  # IMPORTANT: You must specify a StorageClass that exists in your cluster.
  # Find available StorageClasses by running: kubectl get sc
  #storageClassName: longhorn
  storageClassName: local-path
  resources:
    requests:
      storage: 50Gi
