# values.yaml

grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password

# This section is likely for Prometheus Operator's Prometheus instance
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi
