apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  serviceName: "minecraft"
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
       # This section allows the pod to be scheduled on control-plane nodes
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: minecraft
          image: itzg/minecraft-server
          # image: marctv/minecraft-papermc-server:1.21.10
          stdin: true
          tty: true
          envFrom:
            - configMapRef:
                name: minecraft-config
          env:
            - name: ENABLE_RCON
              value: "true"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rcon-password
                  key: SECRET_KEY
          volumeMounts:
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 2
              memory: 4Gi
            limits:
              cpu: 8
              memory: 16Gi
          ports:
          - name: minecraft
            containerPort: 25565
            protocol: TCP
          - name: rcon
            containerPort: 25575
            protocol: TCP
        - name: playit
          image: ghcr.io/playit-cloud/playit-agent:latest
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: playit-gg-secret
                  key: SECRET_KEY
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
