apiVersion: batch/v1
kind: Job
metadata:
  name: script-name-1
  namespace: ai
spec:
  backoffLimit: 1
  template:
    spec:
      nodeSelector:
        kubernetes.io/hostname: "node-hostname"
      restartPolicy: Never
      # 1. ADD: Shared Memory (SHMEM) volume for PyTorch/GPU
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi # Set a size limit for /dev/shm (e.g., 1Gi or 4Gi)
      - name: pvc-storage
        persistentVolumeClaim:
          claimName: ai-pvc
      containers:
      - name: script
        # MetalLB registry ip
        image: 172.16.0.54/script:latest
        imagePullPolicy: Always
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: pvc-storage
          mountPath: /pvc/
