apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-pvc
  namespace: ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi-4
  resources:
    requests:
      storage: 400G
