apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/lucasblopes
  services.yaml: |
    - Homelab:
        - Mealie:
            href: http://172.16.0.124:9000
            description: Delicious recipies

    - Social:
        - Whatsapp:
            href: https://web.whatsapp.com/

        - Slack:
            href: https://app.slack.com/client/TAHV9KXM0/D098DRDCKEY

        - Youtube:
            href: https://youtube.com/

    - My Third Group:
        - My Third Service:
            href: http://localhost/
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
