apiVersion: v1
kind: PersistentVolume
metadata:
  name: nvidia-driver-pv
  namespace: wolf
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nvidia-driver-storage
  hostPath:
    path: /opt/nvidia-drivers
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nvidia-driver-pvc
  namespace: wolf
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nvidia-driver-storage
